name: BungeeHomes
version: '${project.version}'
main: fr.iban.bungeehomes.BungeeHomesPlugin
api-version: 1.17
depend: [ Core ]
authors: [ Iban ]
description: Bungeecord home plugin

commands:
  bhome:
    permission: bungeehomes.home
    aliases:
      - home
  bdelhome:
    permission: bungeehomes.delhome
    aliases:
      - delhome
  bhomes:
    aliases:
      - homes
  bsethome:
    permission: bungeehomes.sethome
    aliases:
      - sethome